### PR TITLE
CI using pocl-cpu.

### PR DESCRIPTION
**Pull request by Kerilk**
This add a working CI that leverages GitHub actions and pocl to test the OpenCL code path.
- Run is 1h
- Building llvm is a couple of hours, but it is cached
- SPIRV-Tools is apparently unneeded, so we may want to remove it to streamline the workflow.

There are many ways we could improve on it I assume, but at least it demonstrates the feasibility of the approach.

### CODE REVIEW

**Comment by pjaaskel** [comment]
Good! We should also add the chipStar tests to the PoCL CI.

**Comment by Kerilk** [comment]
Here is how to integrate the commit hash to the cache, for llvm builds mainly since they may change in the future, but we could generalize for the others so that several versions could be cached:
https://github.com/Kerilk/OpenCL-ICD-Loader/blob/5eb5a5b9d2ac973a6fd2971b9a1ebcef9e1beb51/.github/workflows/linux.yml#L25-L37
```yaml
    - name: Get sha of Headers
      id: get-sha
      run: |
        echo ::set-output name=sha::$( curl -u "u:${{github.token}}" https://api.github.com/repos/KhronosGroup/OpenCL-Headers/git/ref/heads/main | jq .object.sha | tr -d '"' )


    - uses: actions/cache@v2
      name: Cache Headers
      id: headers
      env:
        cache-name: cache-headers
      with:
        path: external/OpenCL-Headers/install
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.get-sha.outputs.sha }}
```

**Comment by pvelesko** [comment]
LGTM - One thing to look out for are some random failures in devicelib tests which occured on cupcake due to what we found out to be the PoCL kernel cache.

**Comment by pjaaskel** [comment]
Could be PoCL kernel cache, or just a timing issue that usually doesn't appear when it has to build the kernel. I suspect the latter as the kcache is old and has been very robust as such. My hunch is more towards the program scope variable support, which is new (and writes something to the cache).

**Comment by pvelesko** [comment]
If I recall correctly all of these segfaults happened inside PoCL when chipStar was executing global variable init ghost funcs

**Comment by pjaaskel** [comment]
Yep, so I suspect it's something timing sensitive with the gvariable init inside PoCL. Your system is the only one I've seen it happen though, rest of us have been luckier so far.

**Pull request merged**
